CREATE TABLE IF NOT EXISTS people.salary_offer (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id integer NOT NULL REFERENCES core.employee(id),
    new_salary double precision NOT NULL,
    new_bonus double precision NULL,
    month_payment_bonus varchar(20) NULL,
    bonus_next_fy double precision NULL,
    new_category varchar(100) NULL,
    observations text NULL,
    aud_user_creation varchar(150) NOT NULL,
    aud_creation_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_salary_offer_new_salary_positive
        CHECK (new_salary > 0),
    CONSTRAINT ck_salary_offer_new_bonus_non_negative
        CHECK (new_bonus IS NULL OR new_bonus >= 0),
    CONSTRAINT ck_salary_offer_bonus_month_required
        CHECK (
            new_bonus IS NULL
            OR length(trim(month_payment_bonus)) > 0
        ),
    CONSTRAINT ck_salary_offer_bonus_next_fy_non_negative
        CHECK (bonus_next_fy IS NULL OR bonus_next_fy >= 0)
);

CREATE INDEX IF NOT EXISTS ix_salary_offer_employee_id
    ON people.salary_offer (employee_id);

CREATE INDEX IF NOT EXISTS ix_salary_offer_aud_creation_at
    ON people.salary_offer (aud_creation_at);
