CREATE SCHEMA IF NOT EXISTS people;

CREATE TABLE IF NOT EXISTS people.salary_offer (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id integer NOT NULL,
    new_salary double precision NOT NULL,
    new_bonus double precision NULL,
    month_payment_bonus varchar(20) NULL,
    bonus_next_fy double precision NULL,
    new_category varchar(100) NULL,
    observations text NULL,
    aud_user_creation varchar(150) NOT NULL,
    aud_creation_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE people.salary_offer
    ADD COLUMN IF NOT EXISTS employee_id integer,
    ADD COLUMN IF NOT EXISTS new_salary double precision,
    ADD COLUMN IF NOT EXISTS new_bonus double precision,
    ADD COLUMN IF NOT EXISTS month_payment_bonus varchar(20),
    ADD COLUMN IF NOT EXISTS bonus_next_fy double precision,
    ADD COLUMN IF NOT EXISTS new_category varchar(100),
    ADD COLUMN IF NOT EXISTS observations text,
    ADD COLUMN IF NOT EXISTS aud_user_creation varchar(150),
    ADD COLUMN IF NOT EXISTS aud_creation_at timestamptz DEFAULT now();

ALTER TABLE people.salary_offer
    ALTER COLUMN employee_id SET NOT NULL,
    ALTER COLUMN new_salary SET NOT NULL,
    ALTER COLUMN aud_user_creation SET NOT NULL,
    ALTER COLUMN aud_creation_at SET DEFAULT now(),
    ALTER COLUMN aud_creation_at SET NOT NULL;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'people'
            AND table_name = 'salary_offer'
            AND column_name = 'id'
            AND is_identity = 'NO'
            AND column_default IS NULL
    ) THEN
        ALTER TABLE people.salary_offer
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'people.salary_offer'::regclass
            AND conname = 'ck_salary_offer_new_salary_positive'
    ) THEN
        ALTER TABLE people.salary_offer
            ADD CONSTRAINT ck_salary_offer_new_salary_positive
            CHECK (new_salary > 0);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'people.salary_offer'::regclass
            AND conname = 'ck_salary_offer_new_bonus_non_negative'
    ) THEN
        ALTER TABLE people.salary_offer
            ADD CONSTRAINT ck_salary_offer_new_bonus_non_negative
            CHECK (new_bonus IS NULL OR new_bonus >= 0);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'people.salary_offer'::regclass
            AND conname = 'ck_salary_offer_bonus_month_required'
    ) THEN
        ALTER TABLE people.salary_offer
            ADD CONSTRAINT ck_salary_offer_bonus_month_required
            CHECK (
                new_bonus IS NULL
                OR length(trim(month_payment_bonus)) > 0
            );
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'people.salary_offer'::regclass
            AND conname = 'ck_salary_offer_bonus_next_fy_non_negative'
    ) THEN
        ALTER TABLE people.salary_offer
            ADD CONSTRAINT ck_salary_offer_bonus_next_fy_non_negative
            CHECK (bonus_next_fy IS NULL OR bonus_next_fy >= 0);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint constraint_record
        JOIN pg_attribute attribute_record
            ON attribute_record.attrelid = constraint_record.conrelid
            AND attribute_record.attnum = ANY(constraint_record.conkey)
        WHERE constraint_record.conrelid = 'people.salary_offer'::regclass
            AND constraint_record.contype = 'f'
            AND attribute_record.attname = 'employee_id'
    ) THEN
        ALTER TABLE people.salary_offer
            ADD CONSTRAINT fk_salary_offer_employee_id
            FOREIGN KEY (employee_id)
            REFERENCES core.employee(id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS ix_salary_offer_employee_id
    ON people.salary_offer (employee_id);

CREATE INDEX IF NOT EXISTS ix_salary_offer_aud_creation_at
    ON people.salary_offer (aud_creation_at);
