from enum import Enum


class SocietyType(str, Enum):
    RSM_SPAIN_ASESORES_LEGALES_Y_TRIBUTARIOS = (
        "RSM SPAIN ASESORES LEGALES Y TRIBUTARIOS, SLP"
    )
    RSM_SPAIN_AUDITORES = "RSM SPAIN AUDITORES, SLP"
    RSM_SPAIN_CONSULTORES = "RSM SPAIN CONSULTORES, SL"
    RSM_SPAIN_CORPORATE_FINANCE = "RSM SPAIN CORPORATE FINANCE, SL"
    RSM_SPAIN_SERVICIOS_ADMINISTRATIVOS = (
        "RSM SPAIN SERVICIOS ADMINISTRATIVOS, SL"
    )


class OfficeName(str, Enum):
    BARCELONA = "Barcelona"
    MADRID = "Madrid"
    VALENCIA = "Valencia"
    SEVILLA = "Sevilla"
    LAS_PALMAS_DE_GRAN_CANARIA = "Las Palmas de Gran Canaria"
    PALMA_DE_MALLORCA = "Palma de Mallorca"
    TARRAGONA = "Tarragona"


class DepartmentType(str, Enum):
    ADMINISTRACION_Y_FINANZAS = "ADMINISTRACIÓN Y FINANZAS"
    CIVIL = "CIVIL"
    CONCURSAL = "CONCURSAL"
    DIGITAL = "DIGITAL"
    FISCAL = "FISCAL"
    KNOWLEDGE_MANAGEMENT = "KNOWLEDGE MANAGEMENT"
    LABORAL = "LABORAL"
    MERCANTIL = "MERCANTIL"
    MIGRATORIO = "MIGRATORIO"
    OUTSOURCING = "OUTSOURCING"
    PAYROLL = "PAYROLL"
    PENAL = "PENAL"
    PROCESAL = "PROCESAL"
    PUBLICO = "PÚBLICO"
    R_D_AND_BUSINESS_INCENTIVES = "R&D AND BUSINESS INCENTIVES"
    REAL_ESTATE = "REAL ESTATE"
    SPORTS = "SPORTS"
    TRANSFER_PRICING = "TRANSFER PRICING"
    AUDITORIA = "AUDITORÍA"
    BPO = "BPO"
    ESG_RSC = "ESG / RSC"
    FORENSIC = "FORENSIC"
    RAS = "RAS"
    BUSINESS_SOLUTIONS = "BUSINESS SOLUTIONS"
    COMUNICACION_Y_MARKETING = "COMUNICACIÓN Y MARKETING"
    PROCESS_AND_DATA_ANALYTICS = "PROCESS & DATA ANALYTICS"
    TECNOLOGIA = "TECNOLOGÍA"
    FAS = "FAS"
    M_A = "M&A"
    CRM_AND_BD = "CRM & BD"
    INNOVACION = "INNOVACIÓN"
    MARKETING_INTERNACIONAL = "MARKETING INTERNACIONAL"
    PEOPLE_AND_CULTURE = "PEOPLE & CULTURE"
    PERSONAS = "PERSONAS"
    PROCESS_AND_DATA_ANALYTICS_E_INNOVACION = (
        "PROCESS & DATA ANALYTICS, INNOVACIÓN"
    )
    RECEPCION = "RECEPCIÓN"
    RRLL = "RRLL"


class CategoryType(str, Enum):
    BECARIO_S_C = "becario s/c"
    BECARIO = "Becario"
    JUNIOR = "Junior"
    SENIOR = "Senior"
    GERENTE = "Gerente"
    DIRECTOR = "Director"
    ESTRUCTURA = "Estructura"
    SOCIO = "Socio"
    COUNSEL = "Counsel"
    AU_EX = "AU/EX"
